server:
  port: 9676

spring:
  #druid
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nl_datapool_db?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: 123456
  #redis
  redis:
    host: 192.168.52.101
    port: 6379
    password: 123456
    database: 9
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0

  #springboot自带的json设置
  jackson:
    default-property-inclusion: non_null #不返回为null的值
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath:mybatis/*Mapper.xml
  type-aliases-package: com.newland.corpxin.model

log-dir: /data3/baidu-company/logs/baidu-company-api/dev/