server:
  port: 8676

spring:
  #druid
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.220:3307/nl_datapool_db?useUnicode=true&amp;characterEncoding=utf8
    username: newland
    password: a8453afa14b65bd8
  #redis
  redis:
    host: 192.168.1.220
    port: 6379
    password: 123456
    database: 9
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
  #springboot自带的json设置
  jackson:
    default-property-inclusion: non_null #不返回为null的值
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath:mybatis/*Mapper.xml
  type-aliases-package: com.newland.pool.baiducompany.model

log-dir: /data1/work/workspace/logs/newland-corpxin-transporter/api/